"""Dump the board history: one SVG per commit.

The board is generated by code, but git holds it already assembled — between
the BOARD:BEGIN/END markers in index.html. So the history of the board is
there already; it only has to be laid out into files for the page to load any
version on demand.

We take what was actually on the site rather than rebuilding the old
generator: a rebuild would give today's look from old code, and what is
wanted is the look that was really seen.
"""

import json
import re
import subprocess
from pathlib import Path

# Путь считается от самого скрипта, а не записан руками: историю теперь
# собирает и CI, а там репозиторий лежит совсем в другом месте.
REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "history"
BOARD = re.compile(r"<!-- BOARD:BEGIN -->(.*?)<!-- BOARD:END -->", re.DOTALL)
VIEWBOX = re.compile(r'<svg viewBox="([^"]+)"[^>]*>\s*<!-- BOARD:BEGIN -->')


def git(*args):
    return subprocess.run(("git", "-C", str(REPO)) + args,
                          capture_output=True, text=True, check=True).stdout


def main():
    OUT.mkdir(exist_ok=True)
    for old in OUT.glob("*.svgz"):
        old.unlink()
    for old in OUT.glob("*.svg"):
        old.unlink()

    log = git("log", "--format=%h\t%ad\t%s", "--date=short", "--reverse", "--", "index.html")
    versions, seen = [], set()
    for line in log.strip().split("\n"):
        sha, date, subject = line.split("\t", 2)
        html = git("show", f"{sha}:index.html")
        m = BOARD.search(html)
        if not m:
            continue                      # commits from before the schematic
        body = m.group(1).strip()
        digest = hash(body)
        if digest in seen:
            continue                      # a rebuild that left the board alone
        seen.add(digest)
        vb = VIEWBOX.search(html)
        name = f"{len(versions):02d}-{sha}.svg"
        (OUT / name).write_text(body, encoding="utf-8")
        versions.append({
            "sha": sha,
            "date": date,
            "subject": subject,
            "file": name,
            "viewBox": vb.group(1) if vb else "-158 -12 1478 887",
            "size": len(body.encode()),
        })

    (OUT / "index.json").write_text(
        json.dumps(versions, ensure_ascii=False, indent=1), encoding="utf-8")
    total = sum(v["size"] for v in versions)
    print(f"versions: {len(versions)}, {total / 1024 / 1024:.1f} MB in total")
    for v in versions:
        print(f'  {v["sha"]} {v["date"]} {v["size"] // 1024:4d} KB  {v["subject"][:56]}')


if __name__ == "__main__":
    main()
